### ISSUE TITLE
Wrong log data when enabling queue

### ISSUE THREAD

**Issue by paales** [firegento/firegento-logger#33] opened 2014-07-16 14:53 UTC
While debugging some issues regarding Loggly I encountered an error.

Queue disabled:
![schermafbeelding 2014-07-16 om 16 51 05](https://cloud.githubusercontent.com/assets/1244416/3600494/d0315842-0cf8-11e4-8f4c-caad2844bd68.png)

Queue enabled:
![schermafbeelding 2014-07-16 om 16 50 18](https://cloud.githubusercontent.com/assets/1244416/3600498/d6fc037a-0cf8-11e4-80ee-f5b32a09d735.png)

**Comment by datenbrille** [comment] 2015-01-24 20:18
Tested and can't reproduce. Can you give me some more data/ information?

**Comment by paales** [comment] 2015-01-26 10:18
@datenbrille Unfortunatly not, we switched over to Loggly shortly after that.

**Comment by datenbrille** [comment] 2015-01-26 15:05
Ok, I will close this issue.

**Closed by datenbrille** 2015-01-26 15:05 UTC
